/* eslint-disable */
DROP DATABASE vidplus;
CREATE DATABASE vidplus;
USE vidplus;

CREATE TABLE users (
  id INT PRIMARY KEY AUTO_INCREMENT,
  email VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  name VARCHAR(255) NOT NULL
);

CREATE TABLE spaces (
  id INT PRIMARY KEY AUTO_INCREMENT,
  url VARCHAR(255) NOT NULL,
  name VARCHAR(255) NOT NULL,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE notes (
  id INT PRIMARY KEY AUTO_INCREMENT,
  space_id INT NOT NULL,
  timestamp VARCHAR(255) NOT NULL,
  content TEXT NOT NULL
);

CREATE TABLE shared (
  user_id INT NOT NULL,
  space_id INT NOT NULL,
  PRIMARY KEY (user_id, space_id)
);